# Generated by Django 4.2 on 2026-04-12 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='market_cart',
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='market_cart_items',
        ),
        migrations.AlterModelTable(
            name='category',
            table='market_categories',
        ),
        migrations.AlterModelTable(
            name='order',
            table='market_orders',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='market_order_items',
        ),
        migrations.AlterModelTable(
            name='product',
            table='market_products',
        ),
        migrations.AlterModelTable(
            name='productimage',
            table='market_product_images',
        ),
        migrations.AlterModelTable(
            name='review',
            table='market_reviews',
        ),
        migrations.AlterModelTable(
            name='user',
            table='market_users',
        ),
    ]
